services:
  - type: web
    name: educore-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
