services:
  - type: web
    name: educore-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install && npm run build
    startCommand: node dist/seed.js && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
